// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXdIIuY2HXFH9TkoVQcEae68pf5McovaQ',
    appId: '1:347367152674:web:54fc36e050f57fd17e7e7b',
    messagingSenderId: '347367152674',
    projectId: 'aroundfast',
    authDomain: 'aroundfast.firebaseapp.com',
    storageBucket: 'aroundfast.firebasestorage.app',
    measurementId: 'G-5WWHNGQ99W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY9J_b7gko3vQNkyhJnuIopNPNcCiURTs',
    appId: '1:347367152674:android:0708fd44dc4633947e7e7b',
    messagingSenderId: '347367152674',
    projectId: 'aroundfast',
    storageBucket: 'aroundfast.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIMjAbyS8A_AySv03Zao7-_bfqVw5e8Lk',
    appId: '1:347367152674:ios:c3113235c3e18d577e7e7b',
    messagingSenderId: '347367152674',
    projectId: 'aroundfast',
    storageBucket: 'aroundfast.firebasestorage.app',
    iosBundleId: 'com.example.flutterHostels',
  );

}